development:
  clients:
    default:
      database: replica_test_db
      hosts:
        - mongo-primary.test.hiogawa.net:27017
        - mongo-secondary.test.hiogawa.net:27017
        - mongo-arbiter.test.hiogawa.net:27017
        - mongo-qingcloud.test.hiogawa.net:27017
      options:
        replica_set: rs0

        user: 'replica_test_db_user'
        password: 'replica_test_db_user'
        roles:
          - 'dbOwner'

        read:
          mode: :nearest
          tag_sets:
            - dc: <%= ENV["MONGO_READ_DC"] %>
test:
  clients:
    default:
      database: puppet_vagrant_cap_rails_app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
